services:
  redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
    environment:
      REDIS_PASSWORD: "password"
      REDIS_PORT: 6379
      REDIS_DATABASES: 1
    volumes:
      - ./docker/.data/redis:/data